# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: meriem
has_binder: false
has_settings: true
kind: frontend
labextension_name: myextension
project_short_description: A JupyterLab extensio
python_name: myextension
repository: ''
test: true

